# Generated by Django 5.2 on 2025-05-29 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip',
            name='lliga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equips', to='futbol.lliga'),
        ),
    ]
